// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zasobowo.API.Data;

#nullable disable

namespace Zasobowo.API.Migrations
{
    [DbContext(typeof(ZasobowoContext))]
    [Migration("20250531125147_ABC")]
    partial class ABC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Zasobowo.API.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Zasobowo.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "1234",
                            Role = "User",
                            Username = "ola.dev"
                        },
                        new
                        {
                            Id = 2,
                            PasswordHash = "1234",
                            Role = "User",
                            Username = "kamil.sys"
                        },
                        new
                        {
                            Id = 3,
                            PasswordHash = "1234",
                            Role = "User",
                            Username = "ania.ui"
                        },
                        new
                        {
                            Id = 4,
                            PasswordHash = "1234",
                            Role = "User",
                            Username = "mario.q"
                        },
                        new
                        {
                            Id = 5,
                            PasswordHash = "1234",
                            Role = "User",
                            Username = "ewelina.pmo"
                        },
                        new
                        {
                            Id = 6,
                            PasswordHash = "1234",
                            Role = "Admin",
                            Username = "dawid.admin"
                        },
                        new
                        {
                            Id = 7,
                            PasswordHash = "1234",
                            Role = "User",
                            Username = "szymon.fullstack"
                        },
                        new
                        {
                            Id = 8,
                            PasswordHash = "1234",
                            Role = "User",
                            Username = "gosia.test"
                        },
                        new
                        {
                            Id = 9,
                            PasswordHash = "1234",
                            Role = "Admin",
                            Username = "adam.secu"
                        },
                        new
                        {
                            Id = 10,
                            PasswordHash = "1234",
                            Role = "User",
                            Username = "karolina.ux"
                        });
                });

            modelBuilder.Entity("Zasobowo.API.Models.Device", b =>
                {
                    b.HasOne("Zasobowo.API.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedUser");
                });
#pragma warning restore 612, 618
        }
    }
}
